name: Run Command on Issue
on:
  issues:
    types: [opened]
jobs:
  run-command:
    if: github.event.issue.title == 'Run the command'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract and Run Command
        id: extract_and_run
        run: |
          issue_body="${{ github.event.issue.body }}" 
          echo "Command from issue: $issue_body"
      - name: Post Job Status Comment
        uses: actions/github-script@v7
        with:
          script: |
            const job_status = '${{ steps.extract_and_run.outcome }}';
            const comment_body = `The command has been executed. Job status: ${job_status}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment_body
            });
      - name: Close Issue
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });
